/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : LEDRed.h
**     Project     : SW2_Projekt
**     Processor   : MKL25Z128VLK4
**     Component   : LED
**     Version     : Component 01.065, Driver 01.00, CPU db: 3.00.000
**     Repository  : My Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2015-09-25, 14:12, # CodeGen: 4
**     Abstract    :
**          This component implements a universal driver for a single LED.
**     Settings    :
**          Component name                                 : LEDRed
**          Turned On with initialization                  : no
**          HW Interface                                   : 
**            Anode on port side, HIGH is ON               : no
**            On/Off                                       : Enabled
**              Pin                                        : LEDpin
**            PWM                                          : Disabled
**          Shell                                          : Disabled
**     Contents    :
**         Init - void LEDRed_Init(void);
**         On   - void LEDRed_On(void);
**         Off  - void LEDRed_Off(void);
**         Neg  - void LEDRed_Neg(void);
**
**     License   : Open Source (LGPL)
**     Copyright : Erich Styger, 2013, all rights reserved.
**     Web       : www.mcuoneclipse.com
**     This an open source software implementing a driver using Processor Expert.
**     This is a free software and is opened for education, research and commercial developments under license policy of following terms:
**     * This is a free software and there is NO WARRANTY.
**     * No restriction on use. You can use, modify and redistribute it for personal, non-profit or commercial product UNDER YOUR RESPONSIBILITY.
**     * Redistributions of source code must retain the above copyright notice.
** ###################################################################*/
/*!
** @file LEDRed.h
** @version 01.00
** @brief
**          This component implements a universal driver for a single LED.
*/         
/*!
**  @addtogroup LEDRed_module LEDRed module documentation
**  @{
*/         

#ifndef __LEDRed_H
#define __LEDRed_H

/* MODULE LEDRed. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "LEDpin1.h"

#include "Cpu.h"

#define LEDRed_ClrVal()    LEDpin1_ClrVal() /* put the pin on low level */
#define LEDRed_SetVal()    LEDpin1_SetVal() /* put the pin on high level */
#define LEDRed_SetInput()  LEDpin1_SetInput() /* use the pin as input pin */
#define LEDRed_SetOutput() LEDpin1_SetOutput() /* use the pin as output pin */

#define LEDRed_PARSE_COMMAND_ENABLED  0 /* set to 1 if method ParseCommand() is present, 0 otherwise */


#define LEDRed_On() LEDpin1_ClrVal()
/*
** ===================================================================
**     Method      :  LEDRed_On (component LED)
**     Description :
**         This turns the LED on.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LEDRed_Off() LEDpin1_SetVal()
/*
** ===================================================================
**     Method      :  LEDRed_Off (component LED)
**     Description :
**         This turns the LED off.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LEDRed_Neg() LEDpin1_NegVal()
/*
** ===================================================================
**     Method      :  LEDRed_Neg (component LED)
**     Description :
**         This negates/toggles the LED
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

#define LEDRed_Init() LEDRed_Off()
/*
** ===================================================================
**     Method      :  LEDRed_Init (component LED)
**     Description :
**         Performs the LED driver initialization.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END LEDRed. */

#endif
/* ifndef __LEDRed_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
